---
title: "Получение сведений о системе"
author: Сафрыгина Анастасия
format: 
    md:
        output-file: README.md
engine: knitr
---

## Цель работы

Получить сведения об используемой системе

## Исходные данные

1. Ноутбук Huawei

2. ОС Windows 11 Домашняя (Ubuntu 22.04.1 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64))

3. Интерпретатор командной оболочки bash

## План

1. Ввод команд в эмулятор терминала

2. Анализ данных

## Ход работы

1. Сначала выполним команду uname -r для вывода информации о системе

```{bash}
uname -r
```


2. Получение сведений о версии ядра:

```{bash}
uname -a
```


3. Получение сведений о процессоре:

```{bash}
cat /proc/cpuinfo | grep "model name"
```

Было определено, что используемый процессор - AMD Ryzen 5 3500U

4. Получение последних 30 строк логов системы:

```{bash}
dmesg | tail -n 30
```

## Оценка результата

По итогам всех выполненных операций в лабораторной работе №1 была получена базовая информация об используемой системе.

## Вывод

Таким образом, мы научились работать с базовыми командами Linux и получать информацию об операционной системе.